#include "HatProjectile.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "TimerManager.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "HarioOdyssey/AreaObject/Player/Player_Mario.h"

// Sets default values
AHatProjectile::AHatProjectile()
{
    PrimaryActorTick.bCanEverTick = true;

    BoxComp = CreateDefaultSubobject<UBoxComponent>(TEXT("BoxComp"));
    SetRootComponent(BoxComp);

    HatMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Hat"));
    HatMesh->SetupAttachment(BoxComp);

    InitialDirection = FVector::ZeroVector;
    
    bSpinning = false;
    bExpanding = false;
    OrbitRadius = 50.0f;
    OrbitSpeed = 360.0f / 1.0f;
    MaxOrbitRadius = 300.0f;
    SpiralSpeed = 100.0f;
    CurrentAngle = 0.0f;
    ExpansionTime = 2.0f;
    CurrentTime = 0.0f;
    bReturning = false;
    bIsThrownStraight = false;
}

// Called when the game starts or when spawned
void AHatProjectile::BeginPlay()
{
    Super::BeginPlay();
    StartLocation = GetActorLocation();
    UE_LOG(LogTemp, Warning, TEXT("ëª¨ì ìƒì„± ì™„ë£Œ, ì´ˆê¸° ìœ„ì¹˜: %s"), *StartLocation.ToString());
}

// Called every frame
void AHatProjectile::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    if (bExpanding) // ğŸ”¹ R í‚¤: ë‚˜ì„ í˜• ê¶¤ì 
    {
        CurrentAngle += OrbitSpeed * DeltaTime;
        if (CurrentAngle >= 360.0f) CurrentAngle -= 360.0f;

        float GrowthFactor = FMath::Clamp(CurrentTime / ExpansionTime, 0.0f, 1.0f);
        OrbitRadius = FMath::Lerp(50.0f, MaxOrbitRadius, GrowthFactor);

        FVector Offset = FVector(
            FMath::Cos(FMath::DegreesToRadians(CurrentAngle)) * OrbitRadius,
            FMath::Sin(FMath::DegreesToRadians(CurrentAngle)) * OrbitRadius,
            0.0f
        );

        if (OwnerActor)
        {
            FVector CenterLocation = OwnerActor->GetActorLocation();
            SetActorLocation(CenterLocation + Offset);
        }

        FRotator Rotation = GetActorRotation();
        Rotation.Yaw += OrbitSpeed * DeltaTime * 3;
        SetActorRotation(Rotation);

        CurrentTime += DeltaTime;
        if (CurrentTime >= ExpansionTime)
        {
            bExpanding = false;
            bReturning = true;
            UE_LOG(LogTemp, Warning, TEXT("ëª¨ì ë‚˜ì„  ì´ë™ ì¢…ë£Œ, ëŒì•„ì˜¤ê¸° ì‹œì‘"));
        }
    }
    else if (bIsThrownStraight) // ğŸ”¹ E í‚¤: ì§ì„  ì´ë™
    {
        FVector NewLocation = GetActorLocation() + (InitialDirection * Speed * DeltaTime);
        SetActorLocation(NewLocation);

        FRotator Rotation = GetActorRotation();
        Rotation.Yaw += OrbitSpeed * DeltaTime * 4;
        SetActorRotation(Rotation);

        CurrentTime += DeltaTime;
        UE_LOG(LogTemp, Warning, TEXT("ëª¨ì ì§ì„  ì´ë™ ì¤‘... í˜„ì¬ ìœ„ì¹˜: %s"), *NewLocation.ToString());

        if (CurrentTime >= FlightTime || FVector::Dist(StartLocation, GetActorLocation()) >= 500.0f)
        {
            UE_LOG(LogTemp, Warning, TEXT("ëª¨ì ì§ì„  ì´ë™ ì¢…ë£Œ, ëŒì•„ì˜¤ê¸° ì‹œì‘"));
            bReturning = true;  
            bIsThrownStraight = false;  // âœ… ì§ì„  ì´ë™ì„ ë©ˆì¶”ê³  ë˜ëŒì•„ì˜¤ëŠ” ìƒíƒœë¡œ ì „í™˜
        }
    }
    else if (bReturning) // ğŸ”¹ ë˜ëŒì•„ì˜¤ëŠ” ìƒíƒœ
    {
        if (OwnerActor)
        {
            FVector DirectionToOwner = (OwnerActor->GetActorLocation() - GetActorLocation()).GetSafeNormal();
            FVector NewLocation = GetActorLocation() + (DirectionToOwner * Speed * 2.0f * DeltaTime); // âœ… ë˜ëŒì•„ì˜¬ ë•Œ ì†ë„ ì¦ê°€
            SetActorLocation(NewLocation);

            UE_LOG(LogTemp, Warning, TEXT("ëª¨ìê°€ ë˜ëŒì•„ì˜¤ëŠ” ì¤‘... ë°©í–¥: %s, í˜„ì¬ ìœ„ì¹˜: %s"), *DirectionToOwner.ToString(), *NewLocation.ToString());

            if (FVector::Dist(OwnerActor->GetActorLocation(), GetActorLocation()) <= 50.0f)
            {
                UE_LOG(LogTemp, Warning, TEXT("ëª¨ìê°€ í”Œë ˆì´ì–´ì—ê²Œ ëŒì•„ì˜´"));
                if (APlayer_Mario* Player = Cast<APlayer_Mario>(OwnerActor))
                {
                    Player->OnHatReturned(this);
                }
                Destroy();
            }
        }
    }
}

// ëª¨ì ë˜ì§ˆ ë•Œ ì´ˆê¸°í™”
void AHatProjectile::InitializeHat(FVector Direction, APlayer_Mario* NewOwner, bool bIsSpinThrow)
{
    InitialDirection = Direction;
    OwnerActor = NewOwner;
    HatMesh->SetSimulatePhysics(true);

    FVector Velocity = Direction * 1000.f;
    HatMesh->AddImpulse(Velocity, NAME_None, true);

    CurrentTime = 0.0f;
    bReturning = false;
    StartLocation = GetActorLocation();

    if (bIsSpinThrow) // ğŸ”¹ R í‚¤ì¼ ë•Œ ë‚˜ì„ í˜• ì ìš©
    {
        bExpanding = true;
        bIsThrownStraight = false;
    }
    else // ğŸ”¹ E í‚¤ì¼ ë•Œ ì§ì„  ì´ë™
    {
        bExpanding = false;
        bIsThrownStraight = true;
    }

    UE_LOG(LogTemp, Warning, TEXT("ëª¨ì ë˜ì§ - bIsSpinThrow: %s"), bIsSpinThrow ? TEXT("true") : TEXT("false"));
}

